source 'http://rubygems.org'
gem 'cucumber' , '2.1.0'
gem 'rspec', '>0'
gem 'watir-webdriver'
gem 'page-object', '=0.7.5.1'
gem 'headless', '>0'
gem 'require_all', '=1.2.1'
gem 'selenium-webdriver'
gem 'data_magic', '>0'
gem 'bundler'
gem 'watir', :platforms => [:mswin, :mingw]
gem 'git'
gem 'pry'
gem 'byebug'
gem 'sauce'
gem 'sauce-connect'
gem 'sauce_whisk'
gem 'temp-mail'
gem 'contextio'
gem 'parallel_tests'
gem 'report_builder'
gem 'faker', '1.6.5'
